[package]
name = "libcrypto"
version = "0.1.0"
edition.workspace = true
publish = false

[lib]
crate-type = ["rlib", "staticlib"]

[features]
deprecated-1-1-0 = []

[dependencies]
ffibox.workspace = true
libc = { path = "../libc" }
libcrypto-sys = { path = "../libcrypto-sys" }

[lints]
workspace = true
